parameters:
    sidus_eav_model.attribute.class: Sidus\EAVModelBundle\Model\Attribute
    sidus_eav_model.family.class: Sidus\EAVModelBundle\Model\Family
    sidus_eav_model.attribute_type_configuration.handler.class: Sidus\EAVModelBundle\Configuration\AttributeTypeConfigurationHandler
    sidus_eav_model.attribute_configuration.handler.class: Sidus\EAVModelBundle\Configuration\AttributeConfigurationHandler
    sidus_eav_model.family_configuration.handler.class: Sidus\EAVModelBundle\Configuration\FamilyConfigurationHandler
    sidus_eav_model.doctrine.repository.data.class: Sidus\EAVModelBundle\Entity\DataRepository
    sidus_eav_model.exception.handler.class: Sidus\EAVModelBundle\Event\ExceptionListener
    sidus_eav_model.validator.sidus_data.class: Sidus\EAVModelBundle\Validator\Constraints\DataValidator
    sidus_eav_model.request.family.param_converter.class: Sidus\EAVModelBundle\Request\ParamConverter\FamilyParamConverter
    sidus_eav_model.request.attribute.param_converter.class: Sidus\EAVModelBundle\Request\ParamConverter\AttributeParamConverter
    sidus_eav_model.serializer.data.subscriber.class: Sidus\EAVModelBundle\Event\DataSerializerHandler
    sidus_eav_model.doctrine.metadata.mapper.class: Sidus\EAVModelBundle\Event\DoctrineMetadataListener

services:
    sidus_eav_model.attribute_type_configuration.handler:
        class: %sidus_eav_model.attribute_type_configuration.handler.class%

    sidus_eav_model.attribute_configuration.handler:
        class: %sidus_eav_model.attribute_configuration.handler.class%

    sidus_eav_model.family_configuration.handler:
        class: %sidus_eav_model.family_configuration.handler.class%
        tags:
            - { name: doctrine.event_listener, event: sidus_family_configuration }

    sidus_eav_model.doctrine.repository.data:
        class: %sidus_eav_model.doctrine.repository.data.class%
        factory_service: doctrine.orm.default_entity_manager
        factory_method: getRepository
        arguments: [%sidus_eav_model.entity.data.class%]

#    Disabling exception listener for now
#    sidus_eav_model.exception.handler:
#        class: %sidus_eav_model.exception.handler.class%
#        arguments: [ @sidus_eav_model.family_configuration.handler, @sidus_eav_model.doctrine.repository.data, @session ]
#        tags:
#            - { name: kernel.event_subscriber }

    sidus_eav_model.validator.sidus_data:
        class: %sidus_eav_model.validator.sidus_data.class%
        arguments: [%sidus_eav_model.entity.data.class%, @sidus_eav_model.family_configuration.handler, @translator, @doctrine]
        tags:
            - { name: validator.constraint_validator, alias: sidus_data }

    sidus_eav_model.request.family.param_converter:
        class: %sidus_eav_model.request.family.param_converter.class%
        arguments: [ @sidus_eav_model.family_configuration.handler ]
        tags:
            - { name: request.param_converter }

    sidus_eav_model.request.attribute.param_converter:
        class: %sidus_eav_model.request.attribute.param_converter.class%
        arguments: [ @sidus_eav_model.attribute_configuration.handler ]
        tags:
            - { name: request.param_converter }

    sidus_eav_model.serializer.data.subscriber.subscriber:
        class: %sidus_eav_model.serializer.data.subscriber.class%
        arguments: [@serializer]
        tags:
            - { name: jms_serializer.event_subscriber }

    sidus_eav_model.doctrine.metadata.mapper:
        class: %sidus_eav_model.doctrine.metadata.mapper.class%
        arguments:
            - %sidus_eav_model.entity.data.class%
            - %sidus_eav_model.entity.value.class%
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }
