parameters:
    sidus_eav_model.denormalizer.data.ignored_attributes:
        - createdBy
        - updatedBy
        - createdAt
        - updatedAt
        - label
        - id
        - identifier # Forbids the usage of the setIdentifier, forces to use the actual attribute instead
        - family
        - familyCode
        - refererValues
        - refererDatas
        - stringIdentifier
        - integerIdentifier
        - values

services:
    Sidus\EAVModelBundle\Serializer\Denormalizer\EAVDataDenormalizer:
        class: Sidus\EAVModelBundle\Serializer\Denormalizer\EAVDataDenormalizer
        parent: serializer.normalizer.object
        arguments:
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
            - '@sidus_eav_model.entity_manager'
            - '@Sidus\EAVModelBundle\Serializer\EntityProviderInterface'
            - '%sidus_eav_model.denormalizer.data.ignored_attributes%'
        tags:
            - { name: serializer.normalizer }

    Sidus\EAVModelBundle\Serializer\Denormalizer\FamilyDenormalizer:
        class: Sidus\EAVModelBundle\Serializer\Denormalizer\FamilyDenormalizer
        arguments:
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
        tags:
            - { name: serializer.normalizer, priority: 2 }
