services:
    Sidus\EAVModelBundle\Form\Extension\LabelTranslationExtension:
        class: Sidus\EAVModelBundle\Form\Extension\LabelTranslationExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Sidus\EAVModelBundle\Form\AttributeFormBuilderInterface:
        alias: Sidus\EAVModelBundle\Form\AttributeFormBuilder

    Sidus\EAVModelBundle\Form\AttributeFormBuilder:
        class: Sidus\EAVModelBundle\Form\AttributeFormBuilder
        public: false
        arguments:
            - '%sidus_eav_model.form.collection_type%'
        calls:
            - [setTranslator, ['@translator']]

    Sidus\EAVModelBundle\Form\AllowedFamiliesOptionsConfigurator:
        class: Sidus\EAVModelBundle\Form\AllowedFamiliesOptionsConfigurator
        public: false
        arguments:
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'

    Sidus\EAVModelBundle\Form\Type\DataType:
        class: Sidus\EAVModelBundle\Form\Type\DataType
        public: false
        arguments:
            - '@Sidus\EAVModelBundle\Form\AttributeFormBuilderInterface'
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
        tags:
            - { name: form.type }

    Sidus\EAVModelBundle\Form\Type\FamilySelectorType:
        class: Sidus\EAVModelBundle\Form\Type\FamilySelectorType
        public: false
        arguments:
            - '@Sidus\EAVModelBundle\Registry\FamilyRegistry'
        tags:
            - { name: form.type }

    Sidus\EAVModelBundle\Form\Type\SimpleDataSelectorType:
        class: Sidus\EAVModelBundle\Form\Type\SimpleDataSelectorType
        public: false
        arguments:
            - '@Sidus\EAVModelBundle\Form\AllowedFamiliesOptionsConfigurator'
            - '@sidus_eav_model.entity_manager'
            - '%sidus_eav_model.entity.data.class%'
        tags:
            - { name: form.type }
