services:
    sidus_eav_model.form.attribute_builder:
        class: Sidus\EAVModelBundle\Form\AttributeFormBuilder
        arguments:
            - '%sidus_eav_model.form.collection_type%'
        calls:
            - [setTranslator, ['@translator']]

    sidus_eav_model.form.type.data:
        class: Sidus\EAVModelBundle\Form\Type\DataType
        arguments:
            - '@sidus_eav_model.form.attribute_builder'
            - '@sidus_eav_model.family.registry'
        tags:
            - { name: form.type }

    sidus_eav_model.form.type.grouped_data:
        class: Sidus\EAVModelBundle\Form\Type\GroupedDataType
        parent: 'sidus_eav_model.form.type.data'
        tags:
            - { name: form.type }

    sidus_eav_model.form.type.family_selector:
        class: Sidus\EAVModelBundle\Form\Type\FamilySelectorType
        arguments: ['@sidus_eav_model.family.registry']
        tags:
            - { name: form.type }

    sidus_eav_model.form.type.simple_data_selector:
        class: Sidus\EAVModelBundle\Form\Type\SimpleDataSelectorType
        arguments:
            - '@sidus_eav_model.family.registry'
            - '%sidus_eav_model.entity.data.class%'
        tags:
            - { name: form.type }

    # Choice extension to handle Doctrine collections
    sidus_eav_model.form.extension.choice:
        class: Sidus\EAVModelBundle\Form\Extension\ChoiceTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ChoiceType }
